### ISSUE TITLE
Error with the script

### ISSUE THREAD

**Issue by daniellages** [itsJarrett/FiveM-boot_vehicles#3]
![unknown](https://user-images.githubusercontent.com/38297483/74360222-978cd100-4dbc-11ea-82f6-140d91984679.png)

Without wanting to disrespect your work, I think that the intructions are unclear.

You say somethin like "Share vehicle files easily, just slap the locations text file in, and add it to the meta!", and I didn't get it.

The way that I installed it was just to put it in my fivem server folder and start it in the server.cfg and then in game I got in a car and did "/gvposa" and it gave me this error.

Can you help me?

**Comment by jimmydesilva** [comment]
It seems another mod you have running has a file named "SetVehicleNumberPlateText.lua" in it that is causing your issue. I just installed boot_vehicles and it's running fine on my end.

**Comment by daniellages** [comment]
Thank you, I'll try that

**Comment by daniellages** [comment]
It didn't work, and I don't have the "SetVehicleNumberPlateText.lua" file: 
https://i.imgur.com/xZdB3pb.png

**Comment by Y0SH1zzzz** [comment]
ever got this to work ?

**Comment by itsJarrett** [comment]
This code is over 4 years old. It will require some overhaul when I get around to it, especially when it comes to the fundamental implementation of the FiveM resource component. Will perhaps get around to it this year.
