### ISSUE TITLE
Ability to set Liveries

### ISSUE THREAD

**Issue by Anters96** [itsJarrett/FiveM-boot_vehicles#4]
This isn't necessarily an issue, but it would be cool if you could set which number livery the vehicle spawns in as.

**Comment by GameCanPlay** [comment]
Found a way. Get in contact with me on discord. GameCanPlay#7022. I would explain here but the script isn't up to date anymore. If you read this feel free to dm me.

> 
> 
> This isn't necessarily an issue, but it would be cool if you could set which number livery the vehicle spawns in as.
