### ISSUE TITLE
vehicles respawn when i use /revive

### ISSUE THREAD

**Issue by karmakarmelo** [itsJarrett/FiveM-boot_vehicles#5]
when I revive more cars are general, does anyone know how to fix that?

AddEventHandler(“playerSpawned”, function(spawnInfo)

if GetNumberOfPlayers() == 1 then

TriggerServerEvent("collectVehicles")
end

end)

I think the problem is in this line, when I revive the game detects that spawn and the event is executed

I don't know if the problem is only mine, but if you can help me with this, I was very grateful

**Comment by cedricalpatch** [comment]
I have same problem, so I dont use the revive if im first player...
Did you have resolve this issu?

**Comment by matsn0w** [comment]
@karmakarmelo @cedricalpatch I've fixed your issue in #8

You can copy/paste my edit in case the PR isn't merged.

(better later than never 😀)
